version: '3.9'

services:
  web:
    build: ./
    container_name: "pegb_web"
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/pegb
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    image: postgres
    container_name: "pegb_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432


  redis:
    container_name: pegb_redis
    image: redis:alpine
    ports:
      - 6381:6379
    volumes:
      - pegb_redis_data:/data
    depends_on:
      - web

  celery-worker:
    container_name: pegb_celery_worker
    restart: always
    build:
      context: .
    command: celery -A config worker -l info
    depends_on:
      - web
      - redis
      - db
    volumes:
      - .:/pegb

  celery-beat:
    container_name: pegb_celery_beat
    restart: always
    build:
      context: .
    command: celery -A config beat -l info
    depends_on:
      - web
      - redis
      - celery-worker
      - db
    volumes:
      - .:/pegb

volumes:
  postgres_data:
  pegb_redis_data:
