# Generated by Django 5.0 on 2023-12-14 00:44

import v1.utils.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', v1.utils.managers.UserManager()),
            ],
        ),
    ]
