# Generated by Django 5.0 on 2023-12-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_category',
            field=models.CharField(blank=True, choices=[('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_category', models.CharField(choices=[('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold')], max_length=6)),
                ('percentage', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
