# Generated by Django 5.0 on 2023-12-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_remove_discount_product_discount_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
